x-shared-logs: &shared-logs
  logging:
    driver: "json-file"
    options:
      max-size: "100k"

services:
  infinity:
    image: michaelf34/infinity:0.0.76
    container_name: infinity
    restart: unless-stopped
    network_mode: host
    profiles:
      - emb
      - full
    command: >
      v2
      --model-id ai-forever/FRIDA
      --engine torch
      --port "7997"
      --url-prefix "/v1"
    environment:
      - HF_HOME=/app/.cache
      - HF_HUB_ENABLE_HF_TRANSFER=0
      - DO_NOT_TRACK=1
      - HF_HUB_DISABLE_TELEMETRY=1
      - INFINITY_ANONYMOUS_USAGE_STATS=0
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./infinity_data:/app/.cache
    runtime: nvidia
    <<: *shared-logs

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.0
    container_name: weaviate
    network_mode: host
    profiles:
      - vdb
      - full
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    restart: unless-stopped
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai"
      OPENAI_APIKEY: "sk-dummy"
      LOG_LEVEL: "debug"
      AUTOSCHEMA_ENABLED: "true"
    volumes:
      - weaviate-data:/var/lib/weaviate
    <<: *shared-logs

  whisper:
    image: fedirz/faster-whisper-server:latest-cuda
    container_name: whisper
    restart: unless-stopped
    network_mode: host
    profiles:
      - asr
      - full
    environment:
      - FASTER_WHISPER_SERVER_PORT=9000
      - WHISPER__MODEL=Systran/faster-whisper-large-v3
      - WHISPER__LANGUAGE=ru
      - WHISPER__INFERENCE_DEVICE=cuda
      - WHISPER__COMPUTE_TYPE=float16
      - WHISPER__BEAM_SIZE=5
      - HOST=0.0.0.0
      - PORT=9000
      - HF_HOME=/root/.cache/huggingface
      - NVIDIA_VISIBLE_DEVICES=1
    volumes:
      - ~/models:/root/.cache/huggingface
    runtime: nvidia
    <<: *shared-logs


volumes:
  weaviate-data: